# Faça um programa que leia um numero Inteiro qualquer
# e mostre na tela a sua tabuada.
n = int(input('Digite um numero de 1 a 10: '))
print('_' * 15)
print('TABUADA DO {}'.format(n))
print('{}  x   1 = {:>3}'.format(n, n*1))
print('{}  x   2 = {:>3}'.format(n, n*2))
print('{}  x   3 = {:>3}'.format(n, n*3))
print('{}  x   4 = {:>3}'.format(n, n*4))
print('{}  x   5 = {:>3}'.format(n, n*5))
print('{}  x   6 = {:>3}'.format(n, n*6))
print('{}  x   7 = {:>3}'.format(n, n*7))
print('{}  x   8 = {:>3}'.format(n, n*8))
print('{}  x   9 = {:>3}'.format(n, n*9))
print('{}  x 10 = {:>2}'.format(n, n*10))
print('_' * 15)
