x = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(x))
print('é alfa-numerico? ', x.isalnum())
print('tem letras maiusculas?', x.isupper())
print('possui só espaço?', x.isspace())
